// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hourlyUnits.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

HourlyUnits _$HourlyUnitsFromJson(Map<String, dynamic> json) => HourlyUnits(
      json['weathercode'] as String?,
      json['et0_fao_evapotranspiration'] as String?,
      json['shortwave_radiation'] as String?,
      json['apparent_temperature'] as String?,
      json['cloudcover'] as String?,
      json['cloudcover_high'] as String?,
      json['cloudcover_low'] as String?,
      json['cloudcover_mid'] as String?,
      json['dewpoint_2m'] as String?,
      json['diffuse_radiation'] as String?,
      json['direct_normal_irradiance'] as String?,
      json['direct_radiation'] as String?,
      json['evapotranspiration'] as String?,
      json['freezinglevel_height'] as String?,
      json['precipitation'] as String?,
      json['pressure_msl'] as String?,
      json['rain'] as String?,
      json['relativehumidity_2m'] as String?,
      json['showers'] as String?,
      json['showsoil_moisture_1_3cmers'] as String?,
      json['snow_depth'] as String?,
      json['snowfall'] as String?,
      json['soil_moisture_0_1cm'] as String?,
      json['soil_moisture_3_9cm'] as String?,
      json['soil_moisture_9_27cm'] as String?,
      json['soil_moisture_27_81cm'] as String?,
      json['soil_temperature_0cm'] as String?,
      json['soil_temperature_6cm'] as String?,
      json['soil_temperature_18cm'] as String?,
      json['soil_temperature_54cm'] as String?,
      json['surface_pressure'] as String?,
      json['temperature_2m'] as String?,
      json['vapor_pressure_deficit'] as String?,
      json['visibility'] as String?,
      json['winddirection_10m'] as String?,
      json['winddirection_80m'] as String?,
      json['winddirection_120m'] as String?,
      json['winddirection_180m'] as String?,
      json['windgusts_10m'] as String?,
      json['windspeed_10m'] as String?,
      json['windspeed_80m'] as String?,
      json['windspeed_120m'] as String?,
      json['windspeed_180m'] as String?,
    );

Map<String, dynamic> _$HourlyUnitsToJson(HourlyUnits instance) =>
    <String, dynamic>{
      'temperature_2m': instance.temperature_2m,
      'relativehumidity_2m': instance.relativehumidity_2m,
      'dewpoint_2m': instance.dewpoint_2m,
      'apparent_temperature': instance.apparent_temperature,
      'pressure_msl': instance.pressure_msl,
      'surface_pressure': instance.surface_pressure,
      'cloudcover': instance.cloudcover,
      'cloudcover_low': instance.cloudcover_low,
      'cloudcover_mid': instance.cloudcover_mid,
      'cloudcover_high': instance.cloudcover_high,
      'windspeed_10m': instance.windspeed_10m,
      'windspeed_80m': instance.windspeed_80m,
      'windspeed_120m': instance.windspeed_120m,
      'windspeed_180m': instance.windspeed_180m,
      'winddirection_10m': instance.winddirection_10m,
      'winddirection_80m': instance.winddirection_80m,
      'winddirection_120m': instance.winddirection_120m,
      'winddirection_180m': instance.winddirection_180m,
      'windgusts_10m': instance.windgusts_10m,
      'shortwave_radiation': instance.shortwave_radiation,
      'direct_radiation': instance.direct_radiation,
      'direct_normal_irradiance': instance.direct_normal_irradiance,
      'diffuse_radiation': instance.diffuse_radiation,
      'vapor_pressure_deficit': instance.vapor_pressure_deficit,
      'evapotranspiration': instance.evapotranspiration,
      'et0_fao_evapotranspiration': instance.et0_fao_evapotranspiration,
      'precipitation': instance.precipitation,
      'snowfall': instance.snowfall,
      'rain': instance.rain,
      'showers': instance.showers,
      'weathercode': instance.weathercode,
      'snow_depth': instance.snow_depth,
      'freezinglevel_height': instance.freezinglevel_height,
      'visibility': instance.visibility,
      'soil_temperature_0cm': instance.soil_temperature_0cm,
      'soil_temperature_6cm': instance.soil_temperature_6cm,
      'soil_temperature_18cm': instance.soil_temperature_18cm,
      'soil_temperature_54cm': instance.soil_temperature_54cm,
      'soil_moisture_0_1cm': instance.soil_moisture_0_1cm,
      'showsoil_moisture_1_3cmers': instance.showsoil_moisture_1_3cmers,
      'soil_moisture_3_9cm': instance.soil_moisture_3_9cm,
      'soil_moisture_9_27cm': instance.soil_moisture_9_27cm,
      'soil_moisture_27_81cm': instance.soil_moisture_27_81cm,
    };
